### ISSUE TITLE
This doesn't seem to switch the quality back anymore

### ISSUE THREAD

**Issue by thinkpad4** [nomomo/Twitch-Auto-Max-Quality#8]
@nomomo @sowind @tryallthethings I've noticed that this isn't switching the quality back to max quality anymore.   

Please see if you can fix it

Thank you very much

**Comment by nomomo** [comment]
Thanks for posting the issue.
I updated the script to v0.2.0 version. Please try again with this.

I'm using Chrome + Tampermonkey, both "Only source quality method" and "Simulate settings button method" work fine.

If your problem is not resolved after updating the script to v0.2.0, please explain in more detail.

Or if you only want the best quality, use the "Only source quality method" in the settings menu.
![image](https://user-images.githubusercontent.com/863079/156708025-12f22d0b-0628-4a45-b4dd-f0d1f9d4560c.png)
![image](https://user-images.githubusercontent.com/863079/156708050-bc3ce5fa-3e9c-412a-a610-30f9b3dde2ee.png)

**Comment by thinkpad4** [comment]
I'll test it out and let you know

**Comment by thinkpad4** [comment]
@nomomo It works perfect again, thank you for fixing it.  Closing this
